### PR TITLE
Fix I18n conflict and add Arabic translation 

### PR DESCRIPTION
**Pull request by MortadaAK**
Fix the conflict by adding prefix **(date_)** in the local files.

Add Arabic translation

### CODE REVIEW

**Comment by mrcasals** [comment]
@MortadaAK thanks for your PR! What is this conflicting with? :)

**Comment by MortadaAK** [comment]
The conflict happens with when using validates_numericality_of on equal_to
You are overwriting the error message by using %{date} instead of %{count}

**Comment by MortadaAK** [comment]
It will fix the problem in issue #76

**Comment by mrcasals** [comment]
@MortadaAK oh thanks, I didn't see that issue! I'll ping @oriolgual and see if we can merge this and publish a new release :)

**Comment by patleb** [comment]
Any chances for the merge to happen?

**Pull request merged**
